spring.application.name=hackathon-hub
spring.main.banner-mode=console

# Logging
logging.level.it.unicam.hackathon=INFO
logging.level.org.springframework=WARN
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [%c{1}] %msg%n
